// Generated by CoffeeScript 1.6.3
(function() {
  var BaseView, HelloView, MainView, mainModule, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mainModule = angular.module('ApplicationMain', []);

  mainModule.config(function($interpolateProvider) {
    $interpolateProvider.startSymbol('[[');
    return $interpolateProvider.endSymbol(']]');
  });

  BaseView = (function() {
    function BaseView() {}

    BaseView.register = function(module) {
      var ctlName, _ref;
      ctlName = (_ref = this.toString().match(/function\s*(.*?)\(/)) != null ? _ref[1] : void 0;
      return module.controller(ctlName, this);
    };

    return BaseView;

  })();

  MainView = (function(_super) {
    __extends(MainView, _super);

    MainView.register(mainModule);

    function MainView() {
      this.tokens = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    }

    return MainView;

  })(BaseView);

  HelloView = (function(_super) {
    __extends(HelloView, _super);

    function HelloView() {
      _ref = HelloView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HelloView.register(mainModule);

    HelloView.prototype.initWithAngle = function(token) {
      return this._setName(token);
    };

    HelloView.prototype._setName = function(token) {
      return this.name = "I'm " + token;
    };

    HelloView.prototype.buttonClicked = function() {
      return this.name = "button was clicked";
    };

    return HelloView;

  })(BaseView);

}).call(this);
