// Generated by CoffeeScript 1.6.3
(function() {
  var MainView, MainViewController,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MainView = (function(_super) {
    __extends(MainView, _super);

    function MainView() {
      var frame, image;
      MainView.__super__.constructor.apply(this, arguments);
      image = new BNImageView();
      frame = {
        'width': '45px',
        'height': '45px'
      };
      image.frame = frame;
      image.src = '/img/logo.png';
      image.circularize = true;
      this.addSubView(image);
    }

    return MainView;

  })(BNView);

  MainViewController = (function(_super) {
    __extends(MainViewController, _super);

    function MainViewController() {
      MainViewController.__super__.constructor.apply(this, arguments);
    }

    MainViewController.prototype.loadView = function() {
      var myView;
      myView = new MainView();
      return this.view = myView;
    };

    return MainViewController;

  })(BNViewController);

  $(document).ready(function() {
    return window.viewController = new MainViewController();
  });

}).call(this);
