// Generated by CoffeeScript 1.6.3
(function() {
  var MainView, MainViewController, MobileFirstView, RootViewController, SubViewController,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MainView = (function(_super) {
    __extends(MainView, _super);

    function MainView() {
      var frame, githubBtnFrame;
      MainView.__super__.constructor.apply(this, arguments);
      this.imageView = new BNImageView();
      frame = {
        x: 0,
        y: 0,
        width: 45,
        height: 45
      };
      this.imageView.frame = frame;
      this.imageView.src = '/img/logo.png';
      this.imageView.circularize = true;
      this.addSubview(this.imageView);
      this.githubBtn = new BNButton();
      this.githubBtn.setTitle("tanB's Github Profile");
      githubBtnFrame = {
        x: 0,
        y: 0,
        width: 160,
        height: 35
      };
      this.githubBtn.frame = githubBtnFrame;
      this.addSubview(this.githubBtn);
    }

    MainView.prototype.layoutSubviews = function() {
      var githubBtnFrame, githubBtnX, githubBtnY, imgFrame, imgX, imgY;
      MainView.__super__.layoutSubviews.apply(this, arguments);
      imgFrame = this.imageView.frame;
      imgX = (this.frame.width - imgFrame.width) / 2;
      imgY = (this.frame.height - imgFrame.height) / 2;
      imgFrame.x = imgX;
      imgFrame.y = imgY;
      this.imageView.frame = imgFrame;
      githubBtnX = this.frame.width - this.githubBtn.frame.width - 8;
      githubBtnY = 8;
      githubBtnFrame = this.githubBtn.frame;
      githubBtnFrame.x = githubBtnX;
      githubBtnFrame.y = githubBtnY;
      return this.githubBtn.frame = githubBtnFrame;
    };

    return MainView;

  })(BNView);

  MobileFirstView = (function(_super) {
    __extends(MobileFirstView, _super);

    function MobileFirstView() {
      MobileFirstView.__super__.constructor.apply(this, arguments);
      this._$elm.css({
        'background-color': 'red'
      });
    }

    MobileFirstView.prototype.layoutSubviews = function() {
      return MobileFirstView.__super__.layoutSubviews.apply(this, arguments);
    };

    return MobileFirstView;

  })(BNView);

  SubViewController = (function(_super) {
    __extends(SubViewController, _super);

    function SubViewController(firstViewController) {
      SubViewController.__super__.constructor.call(this, firstViewController);
    }

    SubViewController.prototype.loadView = function() {
      SubViewController.__super__.loadView.apply(this, arguments);
      return this.view.frame = {
        x: 0,
        y: 0,
        width: 320,
        height: 480
      };
    };

    return SubViewController;

  })(BNNavigationController);

  MainViewController = (function(_super) {
    __extends(MainViewController, _super);

    function MainViewController() {
      MainViewController.__super__.constructor.apply(this, arguments);
    }

    MainViewController.prototype.loadView = function() {
      MainViewController.__super__.loadView.apply(this, arguments);
      return this.view = new MobileFirstView();
    };

    return MainViewController;

  })(BNViewController);

  RootViewController = (function(_super) {
    __extends(RootViewController, _super);

    function RootViewController() {
      var firstViewController;
      RootViewController.__super__.constructor.apply(this, arguments);
      firstViewController = new MainViewController();
      this.subViewController = new SubViewController(firstViewController);
    }

    RootViewController.prototype.loadView = function() {
      var myView;
      RootViewController.__super__.loadView.apply(this, arguments);
      myView = new MainView();
      this.view = myView;
      this.mobileView = this.subViewController.view;
      return this.view.addSubview(this.mobileView);
    };

    RootViewController.prototype.viewDidLoad = function() {
      RootViewController.__super__.viewDidLoad.apply(this, arguments);
      return this.view.githubBtn._$elm.bind('click', function(event) {
        return location.href = 'http://github.com/tanb';
      });
    };

    RootViewController.prototype.didResizeWindow = function(event) {
      return this.layoutSubviews();
    };

    RootViewController.prototype.layoutSubviews = function() {
      var frame, x, y;
      RootViewController.__super__.layoutSubviews.apply(this, arguments);
      x = (this.view.frame.width - this.mobileView.frame.width) / 2;
      y = (this.view.frame.height - this.mobileView.frame.height) / 2;
      frame = this.mobileView.frame;
      frame.x = x;
      frame.y = y;
      this.mobileView.frame = frame;
      return this.subViewController.layoutSubviews();
    };

    return RootViewController;

  })(BNViewController);

  $(document).ready(function() {
    window.rootViewController = new RootViewController();
    return window.addSubview(window.rootViewController.view);
  });

}).call(this);
