// Generated by CoffeeScript 1.6.3
(function() {
  window.BN = {
    '__domain__': 'bluenote'
  };

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  window._subviews = [];

  window.addSubView = function(view) {
    $('body').append(view._$elm);
    return window._subviews.push(view);
  };

  Object.defineProperty(window, 'subviews', {
    get: function() {
      return window._subviews;
    },
    set: function() {}
  });

  BN.View = (function() {
    function View() {
      this._$elm = $('<div />');
      this._$elm.addClass(this.constructor.name);
      this._subviews = [];
    }

    View.property('frame', {
      get: function() {
        var frame;
        frame = {
          width: this._$elm.width(),
          height: this._$elm.height()
        };
        return frame;
      },
      set: function(frame) {
        this._$elm.width(frame.width);
        return this._$elm.height(frame.height);
      }
    });

    View.prototype.addSubView = function(view) {
      this._$elm.append(view._$elm);
      return this._subviews.push(view);
    };

    View.property('subviews', {
      get: function() {
        return this._subviews;
      },
      set: function() {}
    });

    return View;

  })();

  BN.ViewController = (function() {
    function ViewController() {
      this._view = null;
    }

    ViewController.property('view', {
      get: function() {
        if (this._view) {
          return this._view;
        }
        this.loadView();
        this.viewDidLoad();
        return this._view;
      },
      set: function(view) {
        return this._view = view;
      }
    });

    ViewController.prototype.loadView = function() {
      console.log("loadView");
      return this._view = new BN.View();
    };

    ViewController.prototype.viewDidLoad = function() {
      return console.log("viewDidLoad");
    };

    return ViewController;

  })();

}).call(this);
