// Generated by CoffeeScript 1.6.3
(function() {
  var TB,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TB = window;

  TB.View = (function() {
    function View() {
      console.log('TBView');
    }

    return View;

  })();

  TB.CustomView = (function(_super) {
    __extends(CustomView, _super);

    function CustomView() {
      CustomView.__super__.constructor.apply(this, arguments);
      console.log('TBCustomView');
    }

    return CustomView;

  })(TB.View);

}).call(this);
