// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var TB;
    return TB = window;
  });

  Class(TB.Object({
    constructor: function() {
      return this.tag = 0;
    }
  }));

}).call(this);
